# Generated by Django 5.1.5 on 2025-02-07 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
    ]
